entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt

- this allows for more flexibility in how vendorId is filled and transformed all along the transmission chain

feat: case insensitive search of a sensor / device by vendorId #5

---

README.md

Since Stellio has been accepted as an incubated enabler into FIWARE, it should follow the standard badges from the [FIWARE requirements](https://fiware-requirements.rtfd.io/)

Add FIWARE Badges

---

entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityOperationService.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityOperationServiceTests.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt

end of entityOperations/upsert feature

feat(entity): support entityOperations/upsert replace option #21

---

build.gradle.kts
entity-service/src/main/kotlin/com/egm/stellio/entity/config/WebSecurityConfig.kt
entity-service/src/main/resources/application.properties
search-service/src/main/kotlin/com/egm/stellio/search/config/WebSecurityConfig.kt
search-service/src/main/resources/application.properties
subscription-service/src/main/kotlin/com/egm/stellio/subscription/config/WebSecurityConfig.kt
subscription-service/src/main/resources/application.properties

- only activate health endpoint by default
- allow unauthenticated access to enabled endpoints (in production, use a security layer above)
- add exporter for Prometheus metrics

feat: set default conf for actuator endpoints

---

entity-service/src/main/kotlin/com/egm/stellio/entity/model/Attribute.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/model/Property.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/repository/AttributeRepository.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/repository/EntityRepository.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
entity-service/src/main/resources/logback-spring.xml
entity-service/src/main/resources/neo4j/migrations/V02__create_minimal_indexes.cypher
entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
shared/src/main/kotlin/com/egm/stellio/shared/util/NgsiLdParsingUtils.kt

- create properties and relationships of an entity in one Cypher query
- add indexes on entities ids and properties names (the most commonly used)
- improve the efficiency of the entity existence query
- remove customs logs in Neo4jRepository as they can be activated at the Bolt driver level instead
- mark the @Transactional method at the service level as they usually group more than 1 query
- other minor code simplifications

feat(entity): improve queries in entity creation process #70

---

entity-service/src/main/kotlin/com/egm/stellio/entity/repository/EntityRepository.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
entity-service/src/main/resources/neo4j/migrations/V02__create_minimal_indexes.cypher
entity-service/src/main/resources/neo4j/migrations/V03__remove_has_object_relationship_on_entity.cypher
entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt

- use a node label in every MATCH clause
- use params instead of literals in queries (allows caching of query planning by neo4j)
- use existential subqueries to avoid cartesian products in entities search query
- remove HAS_OBJECT relationship between a relationship node and its target entity
- reduce intermediate results when deleting an entity or attribute

feat(entity): improve cypher queries for efficiency #81

---

entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt

- GET or DELETE: get context from Link header or fallback to default JSON-LD @context
- POST or PATH: get context according to content type (error if not provided or mixed)

feat: complete support for JSON-LD @context resolution (6.3.5) #146

---

subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/QueryUtils.kt

The  `"node.get(it) must not be null"` warning is returned when a matching subscription has an unknown attribute in its query.

fix(subscription): fix warning message when a subscription query contains an unknown attribute #144

---

api-gateway/build.gradle.kts
build.gradle.kts
entity-service/build.gradle.kts
search-service/build.gradle.kts
subscription-service/build.gradle.kts

Following suggestions from #160, this PR switches the base image used in Docker images to a distroless version of Java.
It also add standard Docker and OCI labels in the produced images.

feat(common): improve produced Docker images

---

shared/src/main/kotlin/com/egm/stellio/shared/web/AuthUtils.kt
subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt

- currently, if no JWT is retrieved, the flow stops and a 200 status code is returned
- use the same method as in entity service to allow no JWT when auth is disabled

fix: allow to use subscription service when authentication is disabled

---

.github/workflows/cla.yml
Jenkinsfile

Support added in Jenkinsfile:
- when event is a new tag event, extract the tag from Git
- build and publish tagged images in Docker Hub
Still TODO:
- Jenkins receives the push event (`Received Push event for tag v0.0.0.2 in repository stellio-hub/stellio-context-broker CREATED event ...`) ... but does not trigger a build event (`No automatic build triggered for v0.0.0.2`). Some directions to follow: https://notesfromthelifeboat.com/post/building-git-tags-with-jenkins/ (and https://github.com/jenkinsci/basic-branch-build-strategies-plugin)

feat(common): add version tag on docker images #156

---

entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepository.kt

It is not mandatory that an user has personal and group roles ... so don't warn about it.

fix(entity): remove noisy warn message when a group or user role does not exist

---

api-gateway/src/main/resources/application.yml
entity-service/src/main/kotlin/com/egm/stellio/entity/config/WebConfig.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/config/WebSecurityConfig.kt
entity-service/src/main/resources/application.properties
search-service/src/main/kotlin/com/egm/stellio/search/config/WebSecurityConfig.kt
search-service/src/main/resources/application.properties
subscription-service/src/main/kotlin/com/egm/stellio/subscription/config/WebSecurityConfig.kt
subscription-service/src/main/resources/application.properties

The configuration in the api gateway is sufficient to enable CORS in downstream services.
I noticed that a double configuration (in the api gateway and in each downstream service) is not appropriate since the request has been blocked by CORS policy:` The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:3000, http://localhost:3000', but only one is allowed`

feat: add cors configuration in api gateway #295

---

.github/dependabot.yml

Since Dependabot is now available for `build.gradle.kts` files (https://github.blog/changelog/2020-12-18-dependabot-gradle-kotlin-and-composer-v2-support/), adding this action for automatic dependency updates.
See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem for the configuration of the Github Action.

feat: add config file for Dependabot updates

---

build.gradle.kts

See https://github.com/GoogleContainerTools/jib/issues/2966 for details

chore: upgrade Jib to 2.7.1 to fix Java 8 time error

---

docker-compose.yml
search-service/docker-compose.yml
search-service/src/test/kotlin/com/egm/stellio/search/support/WithTimescaleContainer.kt
subscription-service/docker-compose.yml
subscription-service/src/test/kotlin/com/egm/stellio/subscription/support/WithTimescaleContainer.kt

For running instances, procedure is documented on https://stellio.readthedocs.io/en/latest/admin/upgrading_to_1.0.0.html#upgrade-to-timescale-23-postgresql-13

feat: upgrade TimescaleDB to 2.3.0 with PostgreSQL 13

---

entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationService.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/model/Relationship.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/service/SubscriptionHandlerService.kt
entity-service/src/main/resources/neo4j/migrations/V08__add_object_id_in_relationships.cypher
entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepositoryTest.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jSearchRepositoryTests.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/repository/StandaloneNeo4jSearchRepositoryTests.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityAttributeServiceTests.kt

- thus, it avoids doing one more DB request per relationship when retrieving results of a search query

feat(entity): store object of a relationship along with the relationship node

---

docker-compose.yml

- migrations will fail if neo4j is not ready (without failing the app)

feat(entity): wait for an healthy neo4j before starting entity service

---

shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt

- NGSI-LD core context is immutable and it is already cached locally

feat(common): stop loading NGSI-LD core context at startup

---

build.gradle.kts

- https://spring.io/blog/2022/03/01/spring-cloud-gateway-cve-reports-published

chore: upgrade to Spring Cloud 2021.0.1 to apply last CVE

---

entity-service/src/main/kotlin/com/egm/stellio/entity/repository/QueryUtils.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/repository/StandaloneNeo4jSearchRepositoryTests.kt
shared/src/main/kotlin/com/egm/stellio/shared/model/QueryParams.kt

- as per 5.7.2.4, ensure provided ids are URIs, and return a 400 if not

fix(entity): check provided ids are URIs when retrieving entities

---

entity-service/src/main/kotlin/com/egm/stellio/entity/model/AttributeDetails.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/model/AttributeTypeInfo.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/service/AttributeService.kt
entity-service/src/main/kotlin/com/egm/stellio/entity/web/AttributeHandler.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/service/AttributeServiceTest.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/web/AttributeHandlerTests.kt
shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/JsonLdContextUtils.kt

- attribute name and type names must be compacted according to provided context
- fix cast exceptions as neo4j returns sets, not lists
- cleanup unit tests

fix(entity): add missing compaction in attribute info endpoint

---

entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/AuthorizationService.kt

If provided with a minimal entity containing only an id and a type, the previous check was crashing since the list of attributes is empty (and calling `.first()` on an empty list raises an exception).
Instead, just mapping over the list is enough to get the expected result.

fix(entity): handle entities without specific attributes in authz checks

---

search-service/src/main/kotlin/com/egm/stellio/search/service/SubjectReferentialService.kt
search-service/src/main/resources/db/migration/V0_25__swap_client_and_service_account_info.sql
search-service/src/test/kotlin/com/egm/stellio/search/service/SubjectReferentialServiceTests.kt

This is a quick fix to correctly handle the service account id of clients:
- When we get the subject's id along with its groups, we are getting the client id and not the service account id, so the access is denied for clients
- There was a bug in the initializer job as it populated the entity_access_rights table with client ids, and not with service accounts ids (and it works thanks to the problem in the previous point)! To be fixed later for future syncs.
In a near future, this client id / service account id will have to be cleaned up globally as it is currently quite confusing.

fix(search): handling of service account ids when checking rights for clients

---

entity-service/config/detekt/baseline.xml
entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jSearchRepositoryTests.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt

Currently we can make queries with the parameter q, type and/or attrs but also on an id but not on a list of ids.
This feature allows you to make a request on a list of ids.

feat: add the possibility to make queries only on ids

---

entity-service/src/main/kotlin/com/egm/stellio/entity/repository/QueryUtils.kt
entity-service/src/test/kotlin/com/egm/stellio/entity/repository/StandaloneNeo4jSearchRepositoryTests.kt

Quick and dirty solution until we fully and cleanly implement whole support for NGSI-LD Query Langage

hotfix(entity): support case-insensitive regex matching on attributes

---

build.gradle.kts
search-service/build.gradle.kts

- currently includes an outdated and insecure version of org.json:json lib
- did a PR in 08/2022 but got no response so far (https://github.com/savvasdalkitsis/json-merge/pull/2)
- so forked (https://github.com/stellio-hub/json-merge) and published the lib on Jitpack (https://jitpack.io/#stellio-hub/json-merge)

chore: use our own build of json-merge lib

---

subscription-service/src/main/resources/db/migration/V0_17__resize_entity_info_type_column.sql

Size of column was previously 64 chars, which can be a bit short for some long expanded types

chore(subscription): resize type column for entity info

---

.github/workflows/codeql.yml

Put in stand-by since it does not yet support our version of Kotlin (1.8.10)

conf: integrate CodeQL scanning action

---

api-gateway/build.gradle.kts
api-gateway/src/main/kotlin/com/egm/stellio/apigateway/ApiGatewayApplication.kt
api-gateway/src/main/resources/application.yml
api-gateway/src/main/resources/logback-spring.xml

Easier to read logging of requests and responses, for instance:
```
2023-06-03 17:43:31,921 [ctor-http-nio-7] TRACE org.zalando.logbook.Logbook              - write - Incoming Request: bdda58947cdf7e80
Remote: /[0:0:0:0:0:0:0:1]:60943
GET http://localhost:8080/ngsi-ld/v1/entities HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: XXX
Connection: keep-alive
Host: localhost:8080
NGSILD-Tenant: urn:ngsi-ld:tenant:stellio-dev
User-Agent: HTTPie/3.2.2
2023-06-03 17:43:31,922 [ctor-http-nio-7] TRACE org.zalando.logbook.Logbook              - write - Outgoing Response: bdda58947cdf7e80
Duration: 41 ms
HTTP/1.1 400 Bad Request
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Length: 245
Content-Type: application/json
Expires: 0
NGSILD-Tenant: …
```

feat: use Logbook for logging of HTTP requests and responses

---

search-service/src/test/kotlin/com/egm/stellio/search/service/IAMListenerTests.kt
shared/src/main/kotlin/com/egm/stellio/shared/util/JsonUtils.kt
shared/src/testFixtures/resources/ngsild/events/authorization/ClientCreateEventUnknownProperties.json

It is specifically needed before deploying tenants since a new property (`tenantUri`) is added to events sent by KC and it must not break instances that have not yet switched to the version having tenants.

chore: allow unknown properties when unmarshalling to a data class

---

subscription-service/config/detekt/baseline.xml
subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Endpoint.kt
subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
subscription-service/src/main/resources/db/migration/V0_24__update_to_receiver_notifier_info.sql
subscription-service/src/test/kotlin/com/egm/stellio/subscription/job/TimeIntervalNotificationJobTest.kt
subscription-service/src/test/kotlin/com/egm/stellio/subscription/model/SubscriptionTest.kt
subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
subscription-service/src/test/kotlin/com/egm/stellio/subscription/utils/FixtureUtils.kt
subscription-service/src/test/resources/ngsild/subscription_full.json

- was still on pre-1.3 data model with only an info field

feat(subscription): update to receiver / notifier info in notification params

---

search-service/src/main/kotlin/com/egm/stellio/search/config/WebConfig.kt
search-service/src/main/kotlin/com/egm/stellio/search/model/UpdateResult.kt
search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
shared/src/main/kotlin/com/egm/stellio/shared/config/TrailingSlashRedirectFilter.kt
shared/src/main/kotlin/com/egm/stellio/shared/web/ExceptionHandler.kt
subscription-service/src/main/kotlin/com/egm/stellio/subscription/config/WebConfig.kt
subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt

When an attribute is ignored in such an operation, it should not raise an error

fix(core): non existing attrs in append or update operations should be ignored

---

api-gateway/build.gradle.kts
search-service/build.gradle.kts
subscription-service/build.gradle.kts

- let containers use default JVM settings (see https://learn.microsoft.com/en-us/azure/developer/java/containers/overview#understand-jvm-default-ergonomics)
- added instructions in https://stellio.readthedocs.io/en/latest/admin/misc_configuration_tips.html#change-the-jvm-parameters-in-a-container

feat(infra): remove heap size settings from Docker images

---

search-service/src/main/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationService.kt
search-service/src/main/kotlin/com/egm/stellio/search/service/QueryService.kt
search-service/src/main/kotlin/com/egm/stellio/search/util/TemporalEntityBuilder.kt
search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
search-service/src/main/kotlin/db/migration/V0_29__JsonLd_migration.kt
search-service/src/test/kotlin/com/egm/stellio/search/service/QueryServiceTests.kt
search-service/src/test/kotlin/com/egm/stellio/search/util/TemporalEntityBuilderTests.kt
search-service/src/test/kotlin/com/egm/stellio/search/web/EntityAccessControlHandlerTests.kt
search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
search-service/src/test/kotlin/com/egm/stellio/search/web/EntityOperationHandlerTests.kt
search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
shared/src/test/kotlin/com/egm/stellio/shared/model/ExpandedEntityTests.kt
subscription-service/src/main/kotlin/com/egm/stellio/subscription/listener/EntityEventListenerService.kt
subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt

Once an entity is expanded, the contexts used to do the expansion should not be used anymore. So remove them to avoid any misuse of them.

refactor: remove contexts from expanded entity representation

---

search-service/src/main/kotlin/com/egm/stellio/search/common/config/SearchProperties.kt
search-service/src/main/kotlin/com/egm/stellio/search/scope/ScopeService.kt
search-service/src/main/kotlin/com/egm/stellio/search/temporal/service/AttributeInstanceService.kt
search-service/src/main/resources/application.properties
search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/AggregatedTemporalQueryServiceTests.kt
search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/AttributeInstanceServiceTests.kt

By default, bucket start times are aligned at 00:00:00UTC (see https://docs.timescale.com/use-timescale/latest/time-buckets/about-time-buckets/#timezones). This property allows to align them different timezones which is useful for weekly or monthly aggregates for instance.

feat: allow setting a specific timezone for aggregates

---

api-gateway/src/main/kotlin/com/egm/stellio/apigateway/config/FirewallConfig.kt
build.gradle.kts
search-service/src/test/kotlin/com/egm/stellio/search/discovery/web/AttributeHandlerTests.kt
search-service/src/test/kotlin/com/egm/stellio/search/discovery/web/EntityTypeHandlerTests.kt
shared/src/main/kotlin/com/egm/stellio/shared/config/FirewallConfig.kt

The configuration may need further refinement. 
I did a quick review of the specifications to determine what should be permitted.
However, there are several new rules that might cause issues by blocking certain characters:
- the backslash
- the encoded period
or less likely
- the encoded '%'
- the null
- the encoded lineBreaks/tabulations
We could also define a pattern of valid parameter names/value

Upgrade to 3.3.5

---

search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityOperationService.kt
search-service/src/main/kotlin/com/egm/stellio/search/entity/web/BatchAPIResponses.kt
search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandler.kt
search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityOperationServiceTests.kt
search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandlerTests.kt
shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/OptionsValue.kt

- noOverwrite option is not handled whereas it should be passed when in update mode
- replace mode was only replacing the attributes of the entity (and thus was missing all the other needed actions: replace types and scopes, send events...)

fix: incorrect behaviors in Batch Entity Upsert endpoint

---

subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt

Temporary solution while `showChanges` is not implemented. It allows to have access to attributes in case of a `entityDeleted` event. For other events, previous and updated entity are the same.

fix(temp): use deleted entity in notifications

---

docker-compose-dependencies.yml
docker-compose.yml

- mainly to easily launch dependencies only while in development (and launch services in the IDE), without having to comment out the services in the docker compose file

feat: extract dependencies into a specific docker compose file

---

api-gateway/src/main/resources/logback-spring.xml
search-service/src/main/resources/logback-spring.xml
subscription-service/src/main/resources/logback-spring.xml

- see warnings when starting a service:
```
14:45:10,619 |-WARN in org.springframework.boot.logging.logback.SpringProfileIfNestedWithinSecondPhaseElementSanityChecker@2fa60eb1 - <springProfile> elements cannot be nested within an <appender>, <logger> or <root> element
14:45:10,620 |-WARN in org.springframework.boot.logging.logback.SpringProfileIfNestedWithinSecondPhaseElementSanityChecker@2fa60eb1 - Element <root> at line 37 contains a nested <springProfile> element at line 39
```

fix: incorrect structure of logback configuration files

---

subscription-service/build.gradle.kts
subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Subscription.kt

previous changes were not aligned with the specification.
Patch subscription use the 5.5.8 Partial Update Patch Behaviour who work only for one level.

revert multiple level subscription patch
