stellio-hub/stellio-context-broker

- search-service/src/main/resources/db/migration/V0_9__extend_size_type_attribute_name_attribute_value_type_columns.sql
columns : type, attribute_value_type, attribute_name
> fix(search): extend size of stellio_search db columns #84

- entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepository.kt
- entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepositoryTest.kt
- entity-service/src/test/kotlin/com/egm/stellio/entity/service/IAMListenerTests.kt
- entity-service/src/test/resources/ngsild/authorization/RealmRoleAppendEventNoRole.json
- entity-service/src/test/resources/ngsild/authorization/RealmRoleAppendEventOneRole.json
- entity-service/src/test/resources/ngsild/authorization/RealmRoleAppendEventTwoRoles.json
to be merged only after https://github.com/stellio-hub/stellio-context-broker/pull/150 has been merged.
> fix(entity): handle case where an user has a single role

- shared/src/main/kotlin/com/egm/stellio/shared/model/JsonLdEntity.kt
- shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
- shared/src/test/kotlin/com/egm/stellio/shared/util/JsonLdUtilsTests.kt
- subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
- subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/NotificationServiceTests.kt
- subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
- subscription-service/src/test/kotlin/com/egm/stellio/subscription/utils/FixtureUtils.kt
- subscription-service/src/test/kotlin/com/egm/stellio/subscription/utils/QueryUtilsTests.kt
feat(subscriptions): add support for Notification params attributes & format (#32)
> feat(subscription): add support for Notification params attributes & format #32

- kubernetes/api-gateway-deployment.yaml
- kubernetes/entity-service-deployment.yaml
- kubernetes/search-service-deployment.yaml
- kubernetes/stellio-configmap.yaml
- kubernetes/subscription-service-deployment.yaml
> fix(common): use latest tagged images instead of dev #192

- shared/src/main/kotlin/com/egm/stellio/shared/model/APiExceptions.kt
- shared/src/main/kotlin/com/egm/stellio/shared/model/ErrorResponse.kt
- shared/src/main/kotlin/com/egm/stellio/shared/web/ExceptionHandler.kt
- subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
- subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
- raise a 400 if unexpected attribute
- raise a 501 if attribute not yet supported
> feat: better check attributes provided when updating a subscription #354

- .github/ISSUE_TEMPLATE/config.yml
Try to get users to raise Stack Overflow questions properly with appropriate tags.
What types of changes does your code introduce to the project: _Put an `x` in the boxes that apply_
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._
-   [x] I have read the [CONTRIBUTING](https://github.com/stellio-hub/stellio-context-broker/blob/develop/CONTRIBUTING.md) doc
- …
> Add an Issue Template

- config/detekt/detekt.yml
- entity-service/config/detekt/baseline.xml
- search-service/config/detekt/baseline.xml
- shared/config/detekt/baseline.xml
- subscription-service/config/detekt/baseline.xml
- disable LargeClass and TooManyFunctions as it is not really relevant for tests classes
> conf: disable some Detekt rules for tests classes

- entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
JSON-LD @context is in the original entity only when content type is JSON-LD, so ensure we get it from the `NgsiLdEntity` object since it always has it.
> fix(entity): use context from NGSI-LD entity when publishing batch update or upsert event

- entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
- entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
Instead point the relationship to a partial entity with the same id
> feat(entity): no longer remove incoming relationships when deleting an entity

- search-service/src/main/kotlin/com/egm/stellio/search/util/AttributeInstanceUtils.kt
- search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
Quick fix to resolve this problem `https://redmine.eglobalmark.com/issues/3656#change-16188`
> fix: handle boolean when adding attribute instance

- search-service/src/main/kotlin/com/egm/stellio/search/web/AttributeHandler.kt
- search-service/src/main/kotlin/com/egm/stellio/search/web/EntityAccessControlHandler.kt
- search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
- search-service/src/main/kotlin/com/egm/stellio/search/web/EntityOperationHandler.kt
- search-service/src/main/kotlin/com/egm/stellio/search/web/EntityTypeHandler.kt
- search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
- search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityOperationsHandler.kt
- search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
- shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
- shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
- subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
- also harmonize all web handlers wrt use of either effect
> feat: check Link header format

- search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
- search-service/src/main/kotlin/db/migration/V0_29__JsonLd_migration.kt
- shared/src/main/kotlin/com/egm/stellio/shared/util/GeoQueryUtils.kt
- shared/src/test/kotlin/com/egm/stellio/shared/util/GeoQueryUtilsTests.kt
- subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
- prefix explicitly calls to postgis functions with public schema
> fix(tenant): postgis functions are not visible from tenants schemas

- README.md
As discussed within the TSC, badge and links for FIWARE clones of the container image should be switched to quay.io
What types of changes does your code introduce to the project: _Put an `x` in the boxes that apply_
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._
-   [x] I have read the [CONTRIBUTING](https://github.com/stellio-hub/stellio-context-broker/blob/dev …
> Add Quay Badge

- search-service/config/detekt/baseline.xml
- search-service/src/main/kotlin/com/egm/stellio/search/common/model/Query.kt
- search-service/src/main/kotlin/com/egm/stellio/search/entity/model/EntitiesQuery.kt
- search-service/src/main/kotlin/com/egm/stellio/search/entity/service/LinkedEntityService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/entity/util/EntitiesQueryUtils.kt
- search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
- search-service/src/test/kotlin/com/egm/stellio/search/authorization/web/AnonymousUserHandlerTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/service/LinkedEntityServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/util/EntitiesQueryUtilsTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/support/BusinessObjectsFactory.kt
- shared/config/detekt/baseline.xml
- shared/src/main/kotlin/com/egm/stellio/shared/model/CompactedEntity.kt
- shared/src/main/kotlin/com/egm/stellio/shared/model/LinkedEntityQuery.kt
- shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
- shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
- shared/src/main/kotlin/com/egm/stellio/shared/util/LinkedEntityQueryUtils.kt
- shared/src/test/kotlin/com/egm/stellio/shared/model/CompactedEntityFixtureData.kt
- shared/src/test/kotlin/com/egm/stellio/shared/model/CompactedEntityLinkedTests.kt
- shared/src/test/kotlin/com/egm/stellio/shared/model/CompactedEntityTests.kt
- shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/JsonLdContextUtils.kt
- shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/TestUtils.kt
- subscription-service/config/detekt/baseline.xml
- subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
* ~~Asking for the simplified representation should raise an error, to be dealt with in https://github.com/stellio-hub/stellio-context-broker/issues/1207 because it raises a lot of code modifications~~ --> See examples in Annex C for simplified representation 
* [To check] GeoJSON representation does not really work with `flat` join
* [To check] What is the impact on the pagination when asking for `flat` join? (silently add the linked entities but return the expected count of linking entities?)
* Take a (temporary) decision about `containedBy`
> feat(core): Linked Entity Retrieval - Part 1

- search-service/src/main/kotlin/com/egm/stellio/search/csr/service/DistributedEntityProvisionService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
- search-service/src/main/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandler.kt
- search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/EnabledAuthorizationServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistrationTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityOperationServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityQueryServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandlerTests.kt
- shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
- shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedMembers.kt
- shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdEntity.kt
- shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
- shared/src/test/kotlin/com/egm/stellio/shared/model/ExpandedEntityTests.kt
- shared/src/test/kotlin/com/egm/stellio/shared/model/NgsiLdEntityTests.kt
The goal of this PR is to make expandedEntity.id always return an URI
> refactor: expandedEntity id is a uri.

- search-service/src/main/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistration.kt
- search-service/src/main/kotlin/com/egm/stellio/search/csr/model/Operation.kt
- search-service/src/main/kotlin/com/egm/stellio/search/csr/service/DistributedEntityConsumptionService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/csr/service/DistributedEntityProvisionService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/entity/web/BatchAPIResponses.kt
- search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
- search-service/src/test/kotlin/com/egm/stellio/search/csr/service/DistributedEntityProvisionServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
- shared/src/main/kotlin/com/egm/stellio/shared/model/ApiExceptions.kt
still missing :
- test for distributeDeleteEntity()
> feat: distribute delete entity

- api-gateway/Dockerfile
- search-service/Dockerfile
- subscription-service/Dockerfile
See warnings displayed at the bottom of every PR.
> fix(devops): misc changes in Dockerfiles to fix Anchore warnings

- build.gradle.kts
- search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/EntityAccessRightsServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandlerTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityOperationServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/service/LinkedEntityServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandlerTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/temporal/util/TemporalQueryUtilsTests.kt
- subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
- upgrade to last version of mockk.io (since springmockk is not updated for a long time)
> chore: clean and automatically check unnecessary stubs

- search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityQueryService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryService.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryServiceTests.kt
- manually validated, just missing some TCs
> fix(temporal): allow retrieving temporal evolution of an entity when deleted from the current state

- search-service/src/main/kotlin/com/egm/stellio/search/csr/model/CSRFilters.kt
- search-service/src/main/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistration.kt
- search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/csr/service/DistributedEntityConsumptionService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/csr/service/DistributedEntityProvisionService.kt
- search-service/src/main/kotlin/com/egm/stellio/search/csr/web/ContextSourceRegistrationHandler.kt
- search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
- search-service/src/test/kotlin/com/egm/stellio/search/csr/CsrUtils.kt
- search-service/src/test/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistrationTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/csr/service/DistributedEntityConsumptionServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/csr/service/DistributedEntityProvisionServiceTests.kt
- search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
- shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
- shared/src/main/kotlin/com/egm/stellio/shared/util/QueryUtils.kt
filter the distributed consumption operations :
- based on attributes for retrieveEntity.
- based on attributes, entityId, idPattern and types for queryEntities
> feat(csr): implement minimal filters for distributed consumption operations

- search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceQueriesTests.kt
- shared/config/detekt/baseline.xml
- shared/src/main/kotlin/com/egm/stellio/shared/util/QueryUtils.kt
- Intermediate fix until #1144 is done
- Current implementation was error prone so it will also improve user experience
> fix: support queries on relationships with quoted values

- search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationService.kt
- search-service/src/main/kotlin/db/migration/V0_29__JsonLd_migration.kt
- shared/src/main/kotlin/com/egm/stellio/shared/util/QueryUtils.kt
Motivated by the addition of even more list to sql Array transformation with the types and scopes permission implementation.
> refactor: unify list to sql array transformation
